apiVersion: apps/v1
kind: Deployment
metadata:
  name: mello-yello-deploy
  namespace: petrosa-apps
  labels:
    app: mello-yello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yurisa2/petrosa:mello
        ports:
        - containerPort: 80
